### ISSUE TITLE
Support for wiki attachments

### ISSUE THREAD

**Issue by remcoboerma** [nephila/python-taiga#100]
## Description

It would be great to manage wikipage attachments in a similar fashion 

## Use cases

Migrating / syncing wiki pages 

## Proposed solution

Extending the wikipage class with  a `list_attachments`  method 

## Alternatives

Right now, it seems to me i have to parse the HTML of a wikipage and find the URL's of the attachments to get them using requests .

**Comment by protoroto** [comment]
@remcoboerma Hi! We've just released 1.2.0 with this feature.
