### ISSUE TITLE
Missing Info with list functions

### ISSUE THREAD

**Issue by MElborolossy** [nephila/python-taiga#101]
## Description

- According to #52 when using **_list_** function it return the object with less information but when using **_get_** it returns all object information, What I ask about if there is an additional attribute in the listing function to return all information.
- It seems not efficient to **_"Call the same object twice"_**

## Use cases

list_issues, list_user_stories, list_projects, list_users, list_milestones and etc

## Proposed solution

- Add **_full_info_** attribute in the listing function 
- set the default to false if that will help to make it run faster
- if anyone need the full info will pass it true, maybe take longer time but it will be faster than calling the same object twice 
- More efficient: memory, coding and performance wise.

## Alternatives

Make new listing functions that retrieve only the ids as list of int

**Comment by yakky** [comment]
@MElborolossy unfortunately this is a limitation of the underlying Taiga REST API
as python-taiga is just a convenient wrapper around it, there is no way we can achieve this except making the n detail calls ourselves, which would make things more complicated in this library, without any particular gain

**Comment by MElborolossy** [comment]
@yakky Thanks for your comment.
I put a possibility that the limitation come from api.
So it is actually meaningless to modify the whole library.
I will post the issue on the main project of taiga.
