### ISSUE TITLE
Missing description for user stories?

### ISSUE THREAD

**Issue by najarvis** [nephila/python-taiga#105]
## Description
When creating a user story you have the option to specify a description, but when you get the UserStory that is created you can't access that variable. There is a "comment" field, I'm not sure if those are supposed to be the same

## Steps to reproduce
1. Create a user story following the steps here https://pypi.org/project/python-taiga/, make sure to add a description
2. Access the newly created UserStory object and try to find the description you just added.

## Versions

Python version 3.7.3

## Expected behaviour

A 'description' variable that holds the description you just added. You can see it when you access Taiga in the browser, just not in code.

## Actual behaviour

No description.

## Additional information
The comment variable is empty too

**Comment by PeterAlabaster** [comment]
Just noticed this also seems to be the case with the `Issue` object

```python
api.issues.list()[0].description
AttributeError: 'Issue' object has no attribute 'description'
```

Source code looks like it does have handling for this though
Am on `Taiga 6.0.1`

**Comment by PeterAlabaster** [comment]
This might not totally relate to the originally submitted issue, but:

It appears that taiga REST api does not return description on https://docs.taiga.io/api.html#issues-list or https://docs.taiga.io/api.html#user-stories-list so this technically isn't an issue with python-taiga, but the way the Issues, Userstory models in python-taiga are made can lead to the assumption that it should work

The issue, and user-story individual getters do return this, but it leads to very slow performance.
For instance, i can hack it in with
```python
# Issues workaround
[issue.requester.get(f"/issues/{issue.id}").json().get("description") for issue in api.issues.list()]
# User stories workaround
[user_story.requester.get(f"/userstories/{user_story.id}").json().get("description") for user_story in api.user_stories.list()]
```

**Comment by najarvis** [comment]
> It appears that taiga REST api does not return description on https://docs.taiga.io/api.html#issues-list or https://docs.taiga.io/api.html#user-stories-list so this technically isn't an issue with python-taiga

Good find, according to this [google group thread](https://groups.google.com/g/taigaio/c/-IViTo4pJp0/m/SW79bVkKFgAJ) it isn't available in the "list" commands because the descriptions can be very long. It mentions a "detail" call but I'm not seeing a separate "detail" option in the python taiga API itself, so I think your solution of getting the raw JSON and pulling the description is the best we'll get.
