### ISSUE TITLE
Question: Is adding tags to existing user stories currently possible?

### ISSUE THREAD

**Issue by RichardPflaum** [nephila/python-taiga#106]
Hi, is it currently possible to add tags to existing user stories? Or more general, update the UserStory in Taiga following any local changes to the object I have introduced? Thank you!
Best, Richard

**Comment by uc-cjdavis** [comment]
This is possible.  
The `.tags` attribute of a user story is a list and it can be updated using a `['tag name', 'tag color']` list.
Basically:
`userStory.tags.append(tag_list)`

**Comment by RichardPflaum** [comment]
Thank you!
