### ISSUE TITLE
How to get project slug?

### ISSUE THREAD

**Issue by menteora** [nephila/python-taiga#112]
## Description

Hi, I want to get project slug. I need project slug to create full front-end link (eg. https://mytaigahost.com/project/<project_slug>/us/<userstory_id>) of user stories and tasks.
Sorry, but I don't understand how to get it. Can you help me?

## Steps to reproduce

`projects = api.projects.list()`
not return project slug.

## Versions

python-taiga 1.0.0
taiga 6.0.0

**Comment by menteora** [comment]
Hi, the only way I found to get project slug is:

```
projects = api.projects.list()
for project in projects:
      print(api.raw_request.get('projects/{}'.format(project.id)).json()['slug'])
```

**Comment by hardion** [comment]
Hi @menteora ,

From a project I can retrieve by:
```python
projects = api.projects.list()
for project in projects:
    project.slug
```

from a userstory I can retrieve by:
```python
userstories = project.list_user_stories()
for user_story in user_stories:
    user_story.project_extra_info['slug']
```

My 20 cts

**Comment by menteora** [comment]
Thank you very much @hardion !
