### ISSUE TITLE
Missing refresh name:value pair in auth_user_success.json resource

### ISSUE THREAD

**Issue by uc-cjdavis** [nephila/python-taiga#114]
## Description

The tests/resources/auth_user_success.json file used in the tests.test_auth is missing the refresh token name:value pair that is available after a successful auth to the Taiga REST API (ref: https://docs.taiga.io/api.html#object-auth-user-detail).  If the client.auth() function definition is updated to capture the refresh token, the tests.test_auth fails 

## Steps to reproduce

1. Add after line 144 in client.py
   `self.token_refresh = response.json()['refresh']`
3. Run `tox -e pyx.x`

## Versions

Python 3.9
python-taiga latest version

## Expected behaviour

Tests.test_auth.py runs successfully after feature added to code

## Actual behaviour

Test fails

## Additional information

This bug is being filed prior to a PR submission for a fix that will support another PR submission for `refresh` token support.  Capturing the auth returned refresh token will allow for using the refresh auth token endpoint of the Taiga REST API

**Comment by yakky** [comment]
Fixed by #115
