### ISSUE TITLE
Required Param 'moveTo' error message while deleting a user story status

### ISSUE THREAD

**Issue by DomRotbart** [nephila/python-taiga#130]
## Description
I'd like to delete User Story Status(es) by using the Python API.
If I try to delete a Status via API, the console output (error message) says:
`taiga.exceptions.TaigaRestException: Query param 'moveTo' is required`
When inspecting the web request this correlating element is visible, but I didn't find any way to do this via API.

Maybe I'm only using the API in an incorrect way.
But as you can see, in `base.py` the delete function only contains `(self, resource_id)`. Executing the function with more than only the ID to be deleted (say: the "moveTo" ID), the error message says that there are too many params.

## Steps to reproduce
- By creating a fresh Project, predefined UserStoryStatus(es) are created too
- Get a complete list by `api.user_story_statuses.list`
- Try to delete it via `api.user_story_statuses.delete(123)`

## Versions
- Python 3.10.6
- Taiga 6.6.0
- python-taiga 1.1

thanks, br

![api_error_1](https://github.com/nephila/python-taiga/assets/110019211/4a0ae2b5-e1f1-4079-bf8c-349cbea68025)
![function definition](https://github.com/nephila/python-taiga/assets/110019211/c2d5ec8e-254a-4679-9897-bcaaa438717a)
![web request](https://github.com/nephila/python-taiga/assets/110019211/b1bfa9a0-499b-473a-b6ba-6fff73016814)

**Comment by protoroto** [comment]
@DomRotbart Hi! We've just released 1.2.0 with this bug fixed.
