### ISSUE TITLE
RequestMaker broken with requests>=2.11.0

### ISSUE THREAD

**Issue by christophmeissner** [nephila/python-taiga#42]
https://github.com/kennethreitz/requests/commit/2669ab797ce769ecedf5493b04cb976f33e37210 breaks the RequestMaker, as string header values are now enforced with requests >= 2.11.0.

https://github.com/nephila/python-taiga/blob/master/taiga/requestmaker.py#L69 needs to be a string (change to 'True') or else all calls will fail with an RequestException (replaced by an TaigaRestException 'Network error!' for some reason) rendering the library useless with requests>=2.11.0.

**Comment by astagi** [comment]
Fixed by https://github.com/nephila/python-taiga/pull/43
