### ISSUE TITLE
Add capability to retrieve user information.

### ISSUE THREAD

**Issue by dfederschmidt** [nephila/python-taiga#58]
To my understanding there is currently no way of retrieving user information through python-taiga.
A user story has an `assigned_to` field containing the user id of the assigned person. At the moment I'm manually retrieving the user information through the API but it would be nicer to have this functionality inside this package.

**Comment by yakky** [comment]
@dfederschmidt `User` is managed by python-taiga https://github.com/nephila/python-taiga/blob/master/taiga/models/models.py#L107
Yu can just retrieve the user like any other resource.
This is currently not clear from the documentation, but it's going to be fixed by #62

**Comment by menteora** [comment]
Hi, thank you for you library.

I've lost a lot of time to understand how work.

Here's sample, if anyone might need it.
```
api = TaigaAPI(...)
api.users.get(task.assigned_to)
```
