### ISSUE TITLE
Cannot get Ref ID of user stories

### ISSUE THREAD

**Issue by sid2934** [nephila/python-taiga#74]
The attributes that each story in `stories` does not include the ref number of the task.
`stories = taigaBoard.list_user_stories()`

I'm a REST API newbie so if  I am missing something obvious sorry.

**Comment by yakky** [comment]
You should see as `ref` attribute on each us:
```
new_project = api.projects.get_by_slug('my-project')
ref = new_project.list_user_stories()[1]
print(ref.ref)
```

**Comment by yakky** [comment]
closed due to lack of response
