### ISSUE TITLE
AttributeError: 'History' object has no attribute 'id'

### ISSUE THREAD

**Issue by theriverman** [nephila/python-taiga#78]
Hi,

I think one of the latest taiga-back commits broke python-taiga if not entirely but quite badly.
I see they made changes to the history management in taiga-back (they fixed something with timeline history loops on fresh projects) and I suppose it had some effect on this tool.

This gets raised when I'm trying to get a project by its slug:
`AttributeError: 'History' object has no attribute 'id'`

Got no idea where to fix it yet.

**Comment by yakky** [comment]
I cannot reproduce this. Is this something you can consistently reproduce?
Is this against taiga.io setup or self-hosted one?

**Comment by theriverman** [comment]
I haven't used this lib recently so I've just created a fresh virtualenv, installed it from pip and the `api.projects.get_by_slug` method works OK now (against taiga.io).
However, I did the following and I could reproduce the error stated above:
```
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from taiga import TaigaAPI
>>>
>>> api = TaigaAPI()
>>>
>>> api.auth(username='theriverman', password='xxxxxxxxxxxxxxxx')
>>>
>>> api
<taiga.client.TaigaAPI object at 0x000001A7E96A4978>
>>> api.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\theriverman\.virtualenvs\python-taiga-shXUIBGS\lib\site-packages\taiga\models\base.py", line 233, in __repr__
    return '{0}({1})'.format(self.__class__.__name__, self.id)
AttributeError: 'History' object has no attribute 'id'

```

**Comment by yakky** [comment]
Thanks for the information
I will check this

**Comment by yakky** [comment]
@theriverman I have been able to reproduce and it's going to be fixed in #82

**Comment by theriverman** [comment]
Changes look alright to me, @yakky 
Thanks for picking up this issue, I'm closing it.

**Comment by yakky** [comment]
@theriverman thanks for reporting
Expect a release in the next week which will include this fix
