### ISSUE TITLE
Request was throttled.Expected available in 86097 seconds.

### ISSUE THREAD

**Issue by Bowenislandsong** [nephila/python-taiga#79]
I was using this API to send out a massive amount of invites for a class to create public projects and adding members. It throttled at adding members. For some reason, my connection to Taiga Server is extremely slow. I have 100mbps at home and it takes 5 secs to load the website. I am not sure if it has anything to do with it. Thoughts? Thank you!

**Comment by yakky** [comment]
Hi @Bowenislandsong it seems more server related than client on
Any more detailed error / throttling message?
Does this happen against taiga.io or self-hosted instance? which taiga version?

**Comment by Bowenislandsong** [comment]
This was against Taiga.io and it was 2 month ago when i made this comment. So ... 

Thank you,

Bowen Song
 
M.S. Student in ECE at Boston University 
B.Eng in Electrical Engineering at University of Victoria 
1 (857) 244-1271 | sbowen@bu.edu

**Comment by yakky** [comment]
I think taiga.io applies a throttling mechanism. currently python-taiga is just a very tiny wrapper around the REST API provided by taiga, with as little abstraction as possible
thus it's responsibility of the code using python-taiga to handle throttling exceptions and retry whatever action was occurring

**Comment by Bowenislandsong** [comment]
Got it,,, the taiga.io <http://taiga.io/> is rather slow (its web UI) … I understand why they do this. Thank you for explaining it!

**Comment by yakky** [comment]
@Bowenislandsong you're welcome!
