### ISSUE TITLE
UserStory assigned_to return only integer, not list

### ISSUE THREAD

**Issue by menteora** [nephila/python-taiga#93]
Hi, if I get users assigned to specific user story, like this:

`userstory.assigned_to`

if `userstory` is assigned to many users, returns intenger and not list.

Thank you
L.

**Comment by yakky** [comment]
@menteora as documented https://python-taiga.readthedocs.io/en/latest/#taiga.models.models.UserStory taiga report the primary assigned user in `assigned_to` attribute, and all the assigned users in `assigned_users`

As python-taiga is just a tiny wrapper around taiga REST API, we do not try to abstract original structure, and you can refer to the Taiga API documentation http://taigaio.github.io/taiga-doc/dist/api.html (user story body: http://taigaio.github.io/taiga-doc/dist/api.html#object-userstory-detail-get)
